version: '3'

services:
  # COMPOSE FILE IS OUT OF DATE
  reverse-proxy:
    image: nginx:1.25.3-alpine-slim
    container_name: reverse-proxy
    depends_on:
        - quote-app
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443:443'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  # app
  quote-app:
    image: quote-app
    container_name: quote-app
    build:
      context: .
    ports:
      - 8000:8000
    restart: always

  postgres_db:
    image: docker.io/postgres:latest
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    env_file:
      - core/.env

volumes:
  dbdata:
  