version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.1-alpine
    container_name: reverse-proxy
    depends_on:
        - quote-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # app
  quote-app:
    image: quote-app
    container_name: quote-app
    build:
      context: .
    ports:
      - 8000:8000
    restart: always