version: '3'

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.1-alpine
    container_name: reverse-proxy
    depends_on:
        - quote-app
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # app
  quote-app:
    image: quote-app
    container_name: quote-app
    build:
      context: .
    ports:
      - 8000:8000
    restart: always

  postgres_db:
    image: docker.io/postgres:latest
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    env_file:
      - core/.env

volumes:
  dbdata:
  