version: '3'
services:
    nginx-proxy:
        ports:
            - '80:80'
            - '443:443'
        container_name: nginx-proxy
        volumes:
            - '$HOME/certs:/etc/nginx/certs:ro'
            - /etc/nginx/vhost.d
            - ./nginx.conf:/etc/nginx/nginx.conf
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
        image: jwilder/nginx-proxy

    letsencrypt-nginx-proxy-companion:
        ports:
            - '80:80'
            - '443:443'
        container_name: 'nginx-proxy,nginx-letsencrypt'
        volumes:
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - '$HOME/certs:/etc/nginx/certs:rw'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
        image: jrcs/letsencrypt-nginx-proxy-companion

    # nginx:
    #     container_name: site-a
    #     environment:
    #         - LETSENCRYPT_EMAIL=webmaster@example.com
    #         - LETSENCRYPT_HOST=a.example.com
    #         - VIRTUAL_HOST=a.example.com
    #     image: nginx       

    # app
    quote-app:
        image: quote-app
        container_name: quote-app
        build:
          context: .
        restart: always
        environment:
          - VIRTUAL_HOST=quotes.eddyizm.com
          - VIRTUAL_NETWORK=nginx-proxy
          - VIRTUAL_PORT=8000
          - LETSENCRYPT_HOST=quotes.eddyizm.com
          - LETSENCRYPT_EMAIL=eddyizm@gmail.com
        networks:
          - reverse-proxy
