### html gets ###
GET http://127.0.0.1:8000/


### home
GET http://127.0.0.1:8000/home

### random
GET http://127.0.0.1:8000/random

### about 
GET http://127.0.0.1:8000/about

### submissions 
GET http://127.0.0.1:8000/submissions


### api requests ###

# authentication 

### registration
POST http://127.0.0.1:8000/auth/register
content-type: application/json

{
  "email": "user@example.com",
  "password": ""
}

### login with password
POST http://127.0.0.1:8000/auth/login
content-type: application/json

{
  "email": "wtfisup@hotmail.com",
  "password": ""
}

### with token generated 
POST http://127.0.0.1:8000/api/v1/quote/submissions/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODQxMDA2ODMsInN1YiI6Ind0ZmlzdXBAaG90bWFpbC5jb20ifQ.z-TRli43ziit9fkYt6L7Ymf7E61RM0ASGVfTAfFGjE8
  

# open endpoints
### get random quote
POST http://127.0.0.1:8000/api/v1/random/

### get daily quote
POST http://127.0.0.1:8000/api/v1/daily/


### get quote by id
POST http://127.0.0.1:8000/api/v1/quote/817

### send a bad request -> should 404
POST http://127.0.0.1:8000/api/v1/quote/999999

# protected endpoints 

### get list of categories
POST http://127.0.0.1:8000/api/v1/categories/

### get list of authors
POST http://127.0.0.1:8000/api/v1/authors/

### submit new quote
POST http://127.0.0.1:8000/api/v1/quote/submit/
content-type: application/json

{
  "quote": "testing the submission",
  "author": "eddyizm",
  "category": "testing",
  "added_to_quotes": false,
  "added_by": "testing"
}

### get list of quote submissions
POST http://127.0.0.1:8000/api/v1/quote/submissions/
