# html gets
GET http://127.0.0.1:8000/

### api requests ###

### get random quote
POST http://127.0.0.1:8000/api/v1/random/

### get daily quote
POST http://127.0.0.1:8000/api/v1/daily/

### get list of categories
POST http://127.0.0.1:8000/api/v1/categories/

### get list of authors
POST http://127.0.0.1:8000/api/v1/authors/

### submit new quote
POST http://127.0.0.1:8000/api/v1/quote/submit/
content-type: application/json

{
  "quote": "testing the submission",
  "author": "eddyizm",
  "category": "testing",
  "added_to_quotes": false,
  "added_by": "testing"
}

### get list of quote submissions
POST http://127.0.0.1:8000/api/v1/quote/submissions/
